### ISSUE TITLE
How to perform continuous tag inventory in simple java program without an IHM?

### ISSUE THREAD

**Issue by iamadou** [xopxopxop/CAEN_RFID_Controller#1]
Hi,

I am looking a java's program to perform a continuous tag inventory, is it possible to have a help with some code guideline. 

Best regards
Ibrahim

**Comment by xopxopxop** [comment]
Hello iamadou,

This software is very specific for CAEN RFID hardware. I used their API so it's limited to that.

Maybe you could use a thread or task in order to execute it in background.

Best regards,

**Comment by iamadou** [comment]
Hi Sergi,

Thank you for the answer. The hardware I 'm using is CAEN RFID harware,
this is why I have sent this request for you. I dwonload the CAENRFID Lib
jar and I want to perform just continuous inventory but there is no
documentation or an example in the user manual.

Best regards

Ibrahim AMADOU

2017-09-14 7:12 GMT+02:00 Sergi <notifications@github.com>:

**Comment by xopxopxop** [comment]
Hi Ibrahim,

The API documentation talks about "Continuous acquisition" inside "InventoryTag Method". 
There is a flag that represents a bitmask InventoryTag option.

[CAEN RFID API Reference Manual_rev_12.pdf](https://github.com/xopxopxop/CAEN_RFID_Controller/files/1302185/CAEN.RFID.API.Reference.Manual_rev_12.pdf) @ page 30

Best regards,
Sergi

**Comment by iamadou** [comment]
Hi Sergi,

Thank you again, to show how I perform my continuous reading is:

for (int i = 0; i < myReader.GetSources().length; i++)
{
      CAENRFIDLogicalSource mySource = myReader.GetSources()[i];
      System.out.println(mySource.GetName());
      if
(myReader.GetReadPointStatus(myReader.GetReadPoints()[i]).equals(CAENRFIDReadPointStatus.STATUS_GOOD))
      {
          mySource.SetReadCycle(0);
          setInventoryTags(mySource);

      }
}

Then in setInventoryTags:

public static void setInventoryTags(CAENRFIDLogicalSource mySource)
    {
        System.out.println("discover");
        try {
            mySource.SetQ_EPC_C1G2(7);
            byte [] mask = new byte[4];
            CAENRFIDTag[] myTags = mySource.InventoryTag(mask, (short)0,
(short)0, (short)0x07);
            if(myTags != null)
            {
                String[] myInventory = new String[myTags.length];
                int k = 0;
                for (CAENRFIDTag tag: myTags)
                {
                    String epcId = getHex(tag.GetId());
                    double rssiint = tag.GetRSSI() * 0.1;
                    BigDecimal bd = new BigDecimal(rssiint);
                    bd= bd.setScale(3,BigDecimal.ROUND_DOWN);
                    String rssi = Double.toString(bd.doubleValue());
                    String antennas = tag.GetAntenna();
                    String srcName = tag.GetSource().GetName();
                    Date dNow = new Date();
                    SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd
HH:mm:ss.S");
                    ft.setTimeZone(TimeZone.getDefault());
                    String firstSeenTimes = ft.format(dNow);
                    myInventory[k++] = (firstSeenTimes + "#" + epcId + "#"
+ rssi + "#" + "\n");
                }

                for(String myInvTag: myInventory)
                    System.out.println(myInvTag);
            }
        }catch (CAENRFIDException ex) {
            System.out.println(ex);
        }
    }

But it has never performed a continuous inventory and I 'm asking myself if
thre is another way to do it. Thanks again for your help and availability.

Ibrahim AMADOU

2017-09-14 10:00 GMT+02:00 Sergi <notifications@github.com>:

**Comment by xopxopxop** [comment]
Hi Ibrahim,

I worked in that project long time ago but if I remember correctly I had the same problem. I try to perform a continuous tag inventory using the Flag but it was impossible. Finally I gave up, seems that this flag doesn't work properly. If it was me I would try to develop my own continuous tag inventory o maybe you can try to contact CAEN api support. Sorry can't help more.

Best regards,
Sergi
